"""Detect and manage internal transfers between any of the user's accounts
(synced or manually-registered).

Matching first pairs opposite transactions across the user's accounts by exact
amount/currency and nearby posting date. This supports CSV files, which often
do not contain counterparty IBANs and may be imported one account at a time.
Ambiguous amount/date matches are deliberately ignored. As a second signal,
transactions whose `counterparty_iban_hash` matches one of the user's account
`iban_hash` values are linked to that destination account.

A synthetic mirror transaction is created only when the destination is a
manual pocket and no real counterpart exists. Synced/CSV destinations get
their own transaction from their import source.
"""

from __future__ import annotations

import logging
from datetime import timedelta
from typing import Dict, List, Optional
from uuid import UUID

from sqlalchemy.orm import Session, joinedload

from app.models import Account, Category, InternalTransfer, Transaction

logger = logging.getLogger(__name__)


class InternalTransferService:
    """Service for detecting and managing internal transfers.

    Constructor intentionally mirrors the minimal convention used by other
    services: ``(db, user_id)``. No feature flags.
    """

    def __init__(self, db: Session, user_id: str):
        self.db = db
        self.user_id = user_id

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _load_user_account_iban_map(self) -> Dict[str, Account]:
        """Return ``{iban_hash: account}`` for ALL of this user's active accounts
        that have an IBAN hash recorded (synced and manual alike).

        The caller branches on ``account.provider`` to decide whether to mirror
        the transfer (manual destinations, where no other transaction source
        exists) or just tag and link it (synced destinations, where EB delivers
        the destination side's transaction independently).
        """
        accounts = (
            self.db.query(Account)
            .filter(
                Account.user_id == self.user_id,
                Account.iban_hash.isnot(None),
                Account.is_active.is_(True),
            )
            .all()
        )
        # Build the map, but exclude any IBAN hash that maps to more than one
        # account — we can't safely route a transfer to an ambiguous destination.
        seen: Dict[str, Account] = {}
        duplicates: set[str] = set()
        for a in accounts:
            h = a.iban_hash
            if h in seen:
                duplicates.add(h)
            else:
                seen[h] = a
        if duplicates:
            # Don't log raw hashes — they're pseudo-identifiers tied to a
            # specific encryption key and shouldn't end up in log aggregators.
            # Counts + user context are enough to investigate.
            logger.warning(
                "[INTERNAL_TRANSFER] %d IBAN hash(es) map to multiple accounts "
                "for user %s — those hashes will be skipped to avoid mis-routing",
                len(duplicates),
                self.user_id,
            )
        return {h: a for h, a in seen.items() if h not in duplicates}

    def _resolve_transfer_category_id(self) -> Optional[UUID]:
        cat = (
            self.db.query(Category)
            .filter(
                Category.user_id == self.user_id,
                Category.category_type == "transfer",
            )
            .order_by(Category.is_system.desc(), Category.created_at.asc())
            .first()
        )
        return cat.id if cat else None

    @staticmethod
    def _is_synthetic_mirror(transaction: Transaction, source_id: UUID) -> bool:
        """Return whether ``transaction`` was generated by this service."""
        return transaction.external_id == f"mirror-{source_id}"

    def _mark_transaction_as_transfer(
        self,
        transaction: Transaction,
        link_id: UUID,
        transfer_category_id: Optional[UUID],
    ) -> None:
        transaction.include_in_analytics = False
        transaction.internal_transfer_id = link_id
        # Preserve explicit user categorization while replacing automated
        # categorization with the authoritative Transfer category.
        if transfer_category_id and transaction.category_id is None:
            transaction.category_system_id = transfer_category_id

    def _detect_transaction_pairs(
        self,
        transaction_ids: List[UUID],
        transfer_category_id: Optional[UUID],
    ) -> int:
        """Pair imported rows with their opposite side on another account.

        CSV exports commonly omit the destination IBAN. A pair is accepted
        only when there is exactly one eligible transaction with the opposite
        amount, same currency, a different account, and a posting timestamp no
        more than three days away. Requiring a unique candidate avoids turning
        repeated payments (for example two equal card purchases) into false
        transfers.

        Candidates may be newly imported rows, older CSV rows, or a synced
        transaction previously recognized by IBAN. In the last case its
        existing link has ``mirror_txn_id=NULL`` and is completed in place.
        """
        imported = (
            self.db.query(Transaction)
            .filter(
                Transaction.id.in_(transaction_ids),
                Transaction.user_id == self.user_id,
            )
            .order_by(Transaction.booked_at.asc(), Transaction.id.asc())
            .all()
        )
        paired = 0

        for txn in imported:
            if txn.internal_transfer_id is not None or not txn.include_in_analytics:
                continue

            window_start = txn.booked_at - timedelta(days=3)
            window_end = txn.booked_at + timedelta(days=3)
            possible = (
                self.db.query(Transaction)
                .filter(
                    Transaction.user_id == self.user_id,
                    Transaction.id != txn.id,
                    Transaction.account_id != txn.account_id,
                    Transaction.amount == -txn.amount,
                    Transaction.currency == txn.currency,
                    Transaction.booked_at >= window_start,
                    Transaction.booked_at <= window_end,
                )
                .all()
            )

            eligible: list[tuple[Transaction, Optional[InternalTransfer]]] = []
            for candidate in possible:
                if candidate.internal_transfer_id is None:
                    if candidate.include_in_analytics:
                        eligible.append((candidate, None))
                    continue

                # An IBAN match may already have marked the first-imported side
                # before the other account's CSV was uploaded. Complete that
                # link only when it points at this transaction's account.
                existing_link = (
                    self.db.query(InternalTransfer)
                    .filter(
                        InternalTransfer.id == candidate.internal_transfer_id,
                        InternalTransfer.user_id == self.user_id,
                        InternalTransfer.mirror_txn_id.is_(None),
                        InternalTransfer.pocket_account_id == txn.account_id,
                    )
                    .one_or_none()
                )
                if existing_link is not None:
                    eligible.append((candidate, existing_link))

            if len(eligible) != 1:
                if len(eligible) > 1:
                    logger.info(
                        "[INTERNAL_TRANSFER] Skipping ambiguous CSV transfer "
                        "candidate for transaction %s (%d matches)",
                        txn.id,
                        len(eligible),
                    )
                continue

            counterpart, existing_link = eligible[0]
            if existing_link is not None:
                existing_link.mirror_txn_id = txn.id
                self.db.flush()
                self._mark_transaction_as_transfer(txn, existing_link.id, transfer_category_id)
                # The first side was already marked by IBAN detection; apply
                # the category again in case the category was created later.
                self._mark_transaction_as_transfer(
                    counterpart, existing_link.id, transfer_category_id
                )
            else:
                debit = txn if txn.amount < 0 else counterpart
                credit = counterpart if debit is txn else txn
                link = InternalTransfer(
                    user_id=self.user_id,
                    source_txn_id=debit.id,
                    mirror_txn_id=credit.id,
                    source_account_id=debit.account_id,
                    pocket_account_id=credit.account_id,
                    amount=abs(debit.amount),
                    currency=debit.currency,
                )
                self.db.add(link)
                self.db.flush()
                self._mark_transaction_as_transfer(debit, link.id, transfer_category_id)
                self._mark_transaction_as_transfer(credit, link.id, transfer_category_id)

            paired += 1

        return paired

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def detect_for_transactions(self, transaction_ids: List[UUID]) -> dict:
        """Inspect imported transactions for cross-account pairs and IBAN matches.

        Real transaction pairs are linked directly. For an IBAN match targeting
        a manual pocket, create a synthetic mirror transaction on the pocket.

        Returns ``{"detected": int, "pocket_account_ids": list[UUID]}``. The
        ``pocket_account_ids`` set is what callers need to extend their balance
        / timeseries recalculation scope to include touched pockets.

        Only unlinked transactions that are currently
        ``include_in_analytics=True`` are newly considered, so user-hidden rows
        are preserved as-is.
        """
        empty_result = {"detected": 0, "pocket_account_ids": []}
        if not transaction_ids:
            return empty_result

        transfer_category_id = self._resolve_transfer_category_id()
        detected = self._detect_transaction_pairs(transaction_ids, transfer_category_id)

        pocket_map = self._load_user_account_iban_map()
        if not pocket_map:
            if detected:
                self.db.commit()
            return {"detected": detected, "pocket_account_ids": []}

        # Eager-load the source account so we can build a descriptive mirror
        # description without extra queries per-source.
        sources = (
            self.db.query(Transaction)
            .options(joinedload(Transaction.account))
            .filter(
                Transaction.id.in_(transaction_ids),
                Transaction.user_id == self.user_id,
                Transaction.counterparty_iban_hash.isnot(None),
                Transaction.internal_transfer_id.is_(None),
                # Preserve user-hidden rows. Only link transactions currently
                # in analytics — detection sets them to False, and unlink
                # restores them to True (the correct inverse).
                Transaction.include_in_analytics.is_(True),
            )
            .all()
        )

        if transfer_category_id is None:
            logger.warning(
                "[INTERNAL_TRANSFER] No Transfer category found for user %s — "
                "mirror transactions will be created without a system category",
                self.user_id,
            )
        touched_pockets: set = set()

        for src in sources:
            pocket = pocket_map.get(src.counterparty_iban_hash)
            if pocket is None or pocket.id == src.account_id:
                continue

            is_manual = pocket.provider == "manual"

            # Branch on destination provider:
            #  - manual → create mirror so the manual side's balance reflects the transfer
            #  - synced → no mirror (EB delivers that side's transaction independently);
            #    still record an internal_transfers link with mirror_txn_id=NULL so the
            #    unlink endpoint and analytics flag work the same way for both shapes.
            mirror_id: Optional[UUID] = None
            if is_manual:
                mirror_amount = -src.amount
                mirror_functional = (
                    -src.functional_amount if src.functional_amount is not None else None
                )

                src_account_name = getattr(src.account, "name", None) or "account"
                description = (
                    f"Transfer from {src_account_name}"
                    if mirror_amount > 0
                    else f"Transfer to {src_account_name}"
                )

                mirror = Transaction(
                    user_id=self.user_id,
                    account_id=pocket.id,
                    external_id=f"mirror-{src.id}",
                    amount=mirror_amount,
                    currency=src.currency,
                    functional_amount=mirror_functional,
                    description=description,
                    merchant=src_account_name,
                    booked_at=src.booked_at,
                    transaction_type="credit" if mirror_amount > 0 else "debit",
                    category_system_id=transfer_category_id,
                    include_in_analytics=False,
                )
                self.db.add(mirror)
                self.db.flush()  # assigns mirror.id
                mirror_id = mirror.id

            link = InternalTransfer(
                user_id=self.user_id,
                source_txn_id=src.id,
                mirror_txn_id=mirror_id,  # None for synced destinations
                source_account_id=src.account_id,
                pocket_account_id=pocket.id,
                amount=abs(src.amount),
                currency=src.currency,
            )
            self.db.add(link)
            self.db.flush()  # assigns link.id (server_default gen_random_uuid())

            self._mark_transaction_as_transfer(src, link.id, transfer_category_id)

            # Only manual destinations get added to the recalc set — they're the
            # only ones where a mirror transaction was created and the balance
            # needs to be recomputed. Synced destinations get their transactions
            # (and therefore their balance) directly from EB.
            if is_manual:
                touched_pockets.add(pocket.id)
            detected += 1

        if detected:
            self.db.commit()

        logger.info(
            "[INTERNAL_TRANSFER] Detected %d transfer(s) for user %s",
            detected,
            self.user_id,
        )
        return {
            "detected": detected,
            "pocket_account_ids": list(touched_pockets),
        }

    def unlink(self, internal_transfer_id: UUID) -> None:
        """Reverse a single detection: restore the source, delete the mirror,
        and delete the ``internal_transfers`` row.
        """
        link = (
            self.db.query(InternalTransfer)
            .filter(
                InternalTransfer.id == internal_transfer_id,
                InternalTransfer.user_id == self.user_id,
            )
            .one_or_none()
        )
        if link is None:
            return

        src = self.db.query(Transaction).filter(Transaction.id == link.source_txn_id).one_or_none()
        if src is not None:
            src.include_in_analytics = True
            src.internal_transfer_id = None

        if link.mirror_txn_id is not None:
            mirror = (
                self.db.query(Transaction)
                .filter(Transaction.id == link.mirror_txn_id)
                .one_or_none()
            )
            if mirror is not None and src is not None and self._is_synthetic_mirror(mirror, src.id):
                self.db.delete(mirror)
            elif mirror is not None:
                # A CSV/synced counterpart is a real transaction, not a mirror
                # generated by us. Unlink it without deleting user data.
                mirror.include_in_analytics = True
                mirror.internal_transfer_id = None
            else:
                logger.warning(
                    "[INTERNAL_TRANSFER] Mirror %s for link %s already gone — "
                    "link was pointing at a deleted transaction",
                    link.mirror_txn_id,
                    link.id,
                )

        # Flush deletion of the mirror BEFORE deleting the link so the
        # transactions.internal_transfer_id -> internal_transfers.id FK
        # (ON DELETE SET NULL) does not become ambiguous under some drivers.
        self.db.flush()
        self.db.delete(link)
        self.db.commit()

    def unlink_all_for_pocket(self, pocket_account_id: UUID) -> int:
        """Remove all ``internal_transfers`` rows that point at the given account
        as the destination, restoring each source transaction's analytics flag.

        Works for both manual pocket accounts and synced accounts — after the
        recognize-own-IBANs feature, synced accounts can also appear as the
        ``pocket_account_id`` destination of a link.

        **IMPORTANT — call contract:** this is the pre-delete cleanup hook. The
        caller MUST delete the destination account itself immediately after a
        successful return. For manual pockets, mirror transactions on the pocket
        side are NOT deleted here — they depend on the ``ON DELETE CASCADE`` from
        ``transactions.account_id`` when the pocket row is removed. For synced
        destinations ``mirror_txn_id`` is NULL, so there is nothing to cascade.
        If you call this method and do NOT delete the account, orphan mirror
        transactions will remain on manual pockets with no linking
        ``internal_transfers`` row, and analytics will misreport their activity.

        Returns the number of links removed.
        """
        links = (
            self.db.query(InternalTransfer)
            .filter(
                InternalTransfer.pocket_account_id == pocket_account_id,
                InternalTransfer.user_id == self.user_id,
            )
            .all()
        )
        count = 0
        for link in links:
            src = (
                self.db.query(Transaction)
                .filter(Transaction.id == link.source_txn_id)
                .one_or_none()
            )
            if src is not None:
                src.include_in_analytics = True
                src.internal_transfer_id = None
            if link.mirror_txn_id is not None:
                mirror = (
                    self.db.query(Transaction)
                    .filter(Transaction.id == link.mirror_txn_id)
                    .one_or_none()
                )
                if (
                    mirror is not None
                    and src is not None
                    and not self._is_synthetic_mirror(mirror, src.id)
                ):
                    mirror.include_in_analytics = True
                    mirror.internal_transfer_id = None
            self.db.delete(link)
            count += 1

        if count:
            self.db.commit()
        return count
